#! /bin/bash 
#
# SNL-NJOY-2016 generation of manipulate-2020 regression test examples Unix shell
#
  echo ""
  echo "Usage: manipulate-2020_example_support_files called with zero arguments"
  echo ""
#
# Note: Generate support files for the regression tests for manipulate-2020 
#       Later, add a comparison of output files
#
#setenv SYSTEMTYPE unix
export SYSTEMTYPE=unix
# 
# AGENCY must be only 3 characters
#
#setenv AGENCY snl
export AGENCY=snl
#
echo 
echo " Calling location is: $(pwd)"
echo " AGENCY = $AGENCY"
echo " SYSTEMTYPE = $SYSTEMTYPE"
echo 
#
       perl njoy-2016.prl  Ag109_ng_IRDFF-II_cor                    
       perl njoy-2016.prl  Ag109g_IRDFF-II_640grp_xsec   
       perl njoy-2016.prl  S32_np_IRDFF-II_cor           
       perl njoy-2016.prl  S32p_IRDFF-II_640grp_xsec
       perl njoy-2016.prl  Co59_ng_IRDFF-II_cor   
       perl njoy-2016.prl  Co59g_IRDFF-II_640grp_xsec  
       perl njoy-2016.prl  Cf252_640nrg_IRDFF-II_MF33             
       perl njoy-2016.prl  U235_640nrg_IRDFF-II_MF33
#       Note: The fixed.viewer file for the next two calculation needed to be supplied via a hand edit of the baseline viewer file in subdirectory ../output/viewr
#             This change reflects the error message in the input nuclear data files regarding the bad standard deviation in the high energy ()>14-MeV) portion of the source file
       perl njoy-2016.prl  Cf252_640nrg_IRDFF-II_MF33_fixed_viewer   
       perl njoy-2016.prl  U235_640nrg_IRDFF-II_MF33_fixed_viewer    
#  
       perl njoy-2016.prl  Ni58_103_IRDFF-II_640grp_xsec                 
       perl njoy-2016.prl  Ni58_103_IRDFF-II_cor               
       perl njoy-2016.prl  Ni58_103_IRDFF-II_640grp_cov              
echo 
exit #
