#!/bin/bash
#
# NJOY-2016 Unix shell
#
# Note: Linux invocation
#
#echo 
#echo "# NJOY-2016 bash script called with arguments ---> ${@}     "
#echo "#             \$1 -----------------------------> $1       "
#echo 
#ls -la #
#
#SYSTEMTYPE=unix
export SYSTEMTYPE=unix
# 
# AGENCY must be only 3 characters
#AGENCY=snl
export AGENCY=snl
#
echo 
echo " Calling location is: $(pwd)"
echo " AGENCY = $AGENCY"
echo " SYSTEMTYPE = $SYSTEMTYPE"
echo 
perl njoy-2016.prl $1 
#echo " post prl $1" 
echo 
exit #
   
