#!/bin/bash -e 
#
# standard NJOY regression tests - formatted for SNL-NJOY-2016 using a Unix shell
#
echo ""
echo "Usage: standard_NJOY_regression_tests called with zero arguments"
echo ""
#
# Note: Generate the standard set of NJOY regression tests
#       Later, add a comparison of output files
#
export SYSTEMTYPE=unix
# 
# AGENCY must be only 3 characters
#
export AGENCY=snl
#
# check number of input arguments
#
if [ $# -ne 0 ]; then
  echo "Usage: SNL-NJOY-2016 generation of manipulate-2020 regression examples called with Invalid number of arguments $#"
else

  # For all regression input files found within numbered subdirectories, run a test
  for i in ../regression_test_files/*/*.inp; do

    # Current skips are cases 7, 13, 17, 25, and 33 due to infinite loop and large tape files
    if [[ ${i:33:2} != "24" && ${i:33:2} != "25" && ${i:33:2} != "33" ]]; then

      # run the driver script, remove ".inp" from input 
      ./njoy-2016 ${i%.inp}

      # Navigate to regression directory, perform diff on resulting Tape files, return to input directory
      cd ${i%/*}; python3 ../diff.py; cd ../../input
    fi
  done   
fi
