# Install script for directory: /mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/01/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/02/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/03/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/04/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/05/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/06/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/07/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/08/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/09/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/10/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/11/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/12/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/13/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/14/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/15/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/16/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/17/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/18/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/19/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/20/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/21/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/22/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/23/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/24/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/25/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/26/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/27/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/28/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/29/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/30/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/31/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/32/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/33/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/34/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/35/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/36/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/37/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/38/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/39/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/40/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/41/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/42/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/43/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/44/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/45/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/46/cmake_install.cmake")
  include("/mnt/g/sync_Linux/NJOY-2016/Git-Clone/NJOY2016/tests/47/cmake_install.cmake")

endif()

